# Generated by Django 2.2.7 on 2020-07-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity_donation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nazwa instytucji')),
                ('description', models.TextField(verbose_name='Opis')),
                ('type', models.IntegerField(choices=[(1, 'fundacja'), (2, 'organizacja pozarządowa'), (3, 'zbiórka lokalna')], default=1, verbose_name='Rodzaj instytucji')),
                ('categories', models.ManyToManyField(to='charity_donation.Category')),
            ],
        ),
    ]
