# Generated by Django 2.2.7 on 2020-07-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity_donation', '0004_auto_20200703_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default='2020-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donation',
            name='picked_up',
            field=models.BooleanField(default=False, verbose_name='Odebrane'),
        ),
    ]
