# Generated by Django 2.2.7 on 2020-07-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity_donation', '0005_auto_20200712_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='picked_up',
        ),
        migrations.AddField(
            model_name='donation',
            name='status',
            field=models.IntegerField(choices=[(0, 'nieodebrane'), (1, 'odebrane')], default=0),
            preserve_default=False,
        ),
    ]
