# Generated by Django 2.2.7 on 2020-07-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity_donation', '0006_auto_20200712_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.IntegerField(choices=[(0, 'nieodebrane'), (1, 'odebrane')], default=0),
        ),
    ]
