# Generated by Django 2.2.7 on 2020-07-12 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity_donation', '0007_auto_20200712_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='picked_up_date',
            field=models.DateTimeField(null=True, verbose_name='Data odbioru'),
        ),
    ]
