# Generated by Django 2.2.7 on 2020-07-12 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity_donation', '0008_donation_picked_up_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='status',
            new_name='is_taken',
        ),
    ]
